name: Sync docs with gitbook

on:
  push:
    branches: ['github-actions-readme']
    paths: ['docs/snap/**']

jobs:
  copy_cardano_snap_docs:
    name: Copy Cardano Snap Docs
    uses: ./.github/workflows/copy_to_gitbook_repo.yml
    with:
      source_file: 'docs/snap'
      rename: 'metamask-snap-cardano-wallet-coming-soon'
    secrets:
      access_token: ${{ secrets.API_TOKEN_GITHUB }}
